package exactcompiler

import (
	"fmt"
	"sort"
	"strings"

	"github.com/microsoft/typescript-go/internal/ast"
	"github.com/microsoft/typescript-go/internal/checker"
)

type componentBinding struct {
	valueProp            string
	callbackProp         string
	target               *ast.Node
	parameter            *checker.Type
	additionalParameters int
	additionalTypes      []*checker.Type
	write                StateWrite
	start                int
	length               int
}

// analyzeComponentBindings validates component-only value/callback shorthand
// and projects its assignment into ordinary state-write analysis.
func analyzeComponentBindings(
	sourceFile *ast.SourceFile,
	typeChecker *checker.Checker,
	enhancements enhancementImports,
) (map[int]componentBinding, []StateWrite, []Diagnostic) {
	bindings := make(map[int]componentBinding)
	writes := []StateWrite{}
	diagnostics := []Diagnostic{}
	if typeChecker == nil {
		return bindings, writes, diagnostics
	}
	walkNode(sourceFile.AsNode(), func(node *ast.Node) bool {
		if !ast.IsJsxOpeningElement(node) && !ast.IsJsxSelfClosingElement(node) {
			return true
		}
		tagNode := openingTag(node)
		tag := strings.TrimSpace(sourceText(sourceFile, tagNode))
		if jsxIntrinsic(tag) || tag == "_target" {
			return true
		}
		attributes := node.Attributes()
		if attributes == nil {
			return true
		}
		propsType, reason := componentBindingPropsType(tagNode, typeChecker)
		generated := make(map[string]*ast.Node)
		for _, property := range attributes.AsJsxAttributes().Properties.Nodes {
			if !ast.IsJsxAttribute(property) {
				continue
			}
			attribute := property.AsJsxAttribute()
			if !ast.IsJsxNamespacedName(attribute.Name()) {
				continue
			}
			name := attribute.Name().AsJsxNamespacedName()
			valueProp, callbackProp := name.Namespace.Text(), name.Name().Text()
			members := enhancements.applications[attributes.Pos()].attributes[property.Pos()]
			analysisFields := enhancements.analysisFields[property]
			if reason != "" {
				if len(members) != 0 || len(analysisFields) != 0 {
					continue
				}
				diagnostics = append(diagnostics, componentBindingDiagnostic(property, reason))
				continue
			}
			binding, diagnostic := resolveComponentBinding(
				sourceFile,
				property,
				attribute,
				valueProp,
				callbackProp,
				propsType,
				tagNode,
				typeChecker,
			)
			if diagnostic != "" {
				if len(members) != 0 || len(analysisFields) != 0 {
					continue
				}
				diagnostics = append(diagnostics, componentBindingDiagnostic(property, diagnostic))
				continue
			}
			if len(members) != 0 || len(analysisFields) != 0 {
				identities := make([]string, 0, len(members)+len(analysisFields))
				for _, member := range members {
					identities = append(identities, member.identity)
				}
				for _, field := range analysisFields {
					identities = append(identities, field.identity)
				}
				diagnostics = append(diagnostics, componentBindingDiagnostic(
					property,
					fmt.Sprintf(
						"%s:%s is ambiguous between component props %s and %s and enhancement field(s) on %s; expand the binding into explicit props or rename the enhancement namespace",
						valueProp,
						callbackProp,
						valueProp,
						callbackProp,
						strings.Join(identities, ", "),
					),
				))
				continue
			}
			duplicate := false
			for _, generatedProp := range []string{valueProp, callbackProp} {
				if jsxHasAttribute(attributes, generatedProp) {
					diagnostics = append(diagnostics, componentBindingDiagnostic(
						property,
						fmt.Sprintf("%s:%s supplies %s, which is also explicitly authored", valueProp, callbackProp, generatedProp),
					))
					duplicate = true
				}
				if componentBindingFiniteSpreadSupplies(attributes, generatedProp, typeChecker) {
					diagnostics = append(diagnostics, componentBindingDiagnostic(
						property,
						fmt.Sprintf("%s:%s supplies %s, which is also provided by a finite JSX spread", valueProp, callbackProp, generatedProp),
					))
					duplicate = true
				}
				if previous := generated[generatedProp]; previous != nil {
					diagnostics = append(diagnostics, componentBindingDiagnostic(
						property,
						fmt.Sprintf("%s is generated by more than one component binding on this element", generatedProp),
					))
					duplicate = true
				}
			}
			if duplicate {
				continue
			}
			generated[valueProp] = property
			generated[callbackProp] = property
			bindings[property.Pos()] = binding
			writes = append(writes, binding.write)
		}
		return true
	})
	return bindings, writes, diagnostics
}

func componentBindingFiniteSpreadSupplies(
	attributes *ast.Node,
	name string,
	typeChecker *checker.Checker,
) bool {
	for _, property := range attributes.AsJsxAttributes().Properties.Nodes {
		if !ast.IsJsxSpreadAttribute(property) {
			continue
		}
		members := typeChecker.GetTypeAtLocation(property.AsJsxSpreadAttribute().Expression).Distributed()
		if len(members) == 0 {
			continue
		}
		provided := true
		for _, member := range members {
			if len(typeChecker.GetIndexInfosOfType(member)) != 0 {
				provided = false
				break
			}
			symbol := typeChecker.GetPropertyOfType(member, name)
			if symbol == nil || symbol.Flags&ast.SymbolFlagsOptional != 0 {
				provided = false
				break
			}
		}
		if provided {
			return true
		}
	}
	return false
}

func componentBindingPropsType(
	tag *ast.Node,
	typeChecker *checker.Checker,
) (*checker.Type, string) {
	componentType := typeChecker.GetTypeAtLocation(tag)
	signatures := typeChecker.GetSignaturesOfType(componentType, checker.SignatureKindCall)
	if len(signatures) != 1 || len(signatures[0].Parameters()) == 0 {
		return nil, "component binding shorthand requires one finite component call signature with public props"
	}
	propsType := typeChecker.GetTypeOfSymbolAtLocation(signatures[0].Parameters()[0], tag)
	for _, member := range propsType.Distributed() {
		if len(typeChecker.GetIndexInfosOfType(member)) != 0 {
			return nil, "component binding shorthand requires a finite prop type without an index signature"
		}
	}
	return propsType, ""
}

func resolveComponentBinding(
	sourceFile *ast.SourceFile,
	node *ast.Node,
	attribute *ast.JsxAttribute,
	valueProp string,
	callbackProp string,
	propsType *checker.Type,
	componentTag *ast.Node,
	typeChecker *checker.Checker,
) (componentBinding, string) {
	if valueProp == callbackProp {
		return componentBinding{}, "component binding value and callback props must be different"
	}
	valueSymbol := typeChecker.GetPropertyOfType(propsType, valueProp)
	if valueSymbol == nil {
		return componentBinding{}, fmt.Sprintf("component has no finite %s value prop", valueProp)
	}
	callbackSymbol := typeChecker.GetPropertyOfType(propsType, callbackProp)
	if callbackSymbol == nil {
		return componentBinding{}, fmt.Sprintf("component has no finite %s callback prop", callbackProp)
	}
	if attribute.Initializer == nil || !ast.IsJsxExpression(attribute.Initializer) {
		return componentBinding{}, valueProp + ":" + callbackProp + " requires one writable reactive state location"
	}
	target := attribute.Initializer.AsJsxExpression().Expression
	if target == nil || (!ast.IsPropertyAccessExpression(target) && !ast.IsElementAccessExpression(target)) {
		return componentBinding{}, valueProp + ":" + callbackProp + " requires one writable reactive state location"
	}
	write, ok := componentBindingStateWrite(sourceFile, target, typeChecker)
	if !ok || len(write.Path) == 0 {
		return componentBinding{}, valueProp + ":" + callbackProp + " requires one compiler-proven writable state location"
	}
	valueType := componentBindingSymbolType(valueSymbol, componentTag, typeChecker)
	targetType := typeChecker.GetTypeAtLocation(target)
	if !typeChecker.IsTypeAssignableTo(targetType, valueType) {
		return componentBinding{}, fmt.Sprintf("state value %s is not assignable to component prop %s", typeChecker.TypeToString(targetType), valueProp)
	}
	callbackType := componentBindingSymbolType(callbackSymbol, componentTag, typeChecker)
	if typeContainsFlag(callbackType, checker.TypeFlagsNull) {
		return componentBinding{}, callbackProp + " must be a callable prop with only optional undefined"
	}
	callbackType = typeChecker.GetNonNullableType(callbackType)
	signatures := typeChecker.GetSignaturesOfType(callbackType, checker.SignatureKindCall)
	if len(signatures) != 1 {
		return componentBinding{}, callbackProp + " must have one unambiguous call signature"
	}
	signature := signatures[0]
	if signature.MinArgumentCount() < 1 || len(signature.Parameters()) == 0 {
		return componentBinding{}, callbackProp + " must have one required replacement-value parameter"
	}
	parameterType := componentBindingSymbolType(signature.Parameters()[0], componentTag, typeChecker)
	if !typeChecker.IsTypeAssignableTo(parameterType, targetType) {
		return componentBinding{}, fmt.Sprintf("callback value %s is not assignable to state location %s", typeChecker.TypeToString(parameterType), typeChecker.TypeToString(targetType))
	}
	if !notificationReturnType(typeChecker.GetReturnTypeOfSignature(signature)) {
		return componentBinding{}, callbackProp + " must return only void or undefined; semantic callback results require explicit source"
	}
	additionalTypes := make([]*checker.Type, 0, len(signature.Parameters())-1)
	for _, additional := range signature.Parameters()[1:] {
		additionalTypes = append(
			additionalTypes,
			componentBindingSymbolType(additional, componentTag, typeChecker),
		)
	}
	return componentBinding{
		valueProp: valueProp, callbackProp: callbackProp, target: target,
		parameter: parameterType, write: write,
		additionalParameters: len(signature.Parameters()) - 1,
		additionalTypes:      additionalTypes,
		start:                node.Pos(), length: node.End() - node.Pos(),
	}, ""
}

func componentBindingSymbolType(
	symbol *ast.Symbol,
	fallback *ast.Node,
	typeChecker *checker.Checker,
) *checker.Type {
	location := fallback
	if symbol != nil && symbol.ValueDeclaration != nil {
		location = symbol.ValueDeclaration
	}
	return typeChecker.GetTypeOfSymbolAtLocation(symbol, location)
}

func collectValueCallbackBindings(
	componentBindings map[int]componentBinding,
	formBindings map[int]formBinding,
	components []Component,
	typeChecker *checker.Checker,
) []ValueCallbackBinding {
	componentByName := make(map[string]Component, len(components))
	for _, component := range components {
		componentByName[component.Name] = component
	}
	result := make([]ValueCallbackBinding, 0, len(componentBindings)+len(formBindings))
	for _, binding := range componentBindings {
		owner := componentByName[binding.write.Component]
		additionalTypes := make([]string, 0, len(binding.additionalTypes))
		for _, parameterType := range binding.additionalTypes {
			additionalTypes = append(additionalTypes, typeChecker.TypeToString(parameterType))
		}
		result = append(result, ValueCallbackBinding{
			Component: binding.write.Component, StatePath: append([]string(nil), binding.write.Path...),
			ValueProp: binding.valueProp, CallbackProp: binding.callbackProp,
			CallbackValueType:        typeChecker.TypeToString(binding.parameter),
			AdditionalParameters:     binding.additionalParameters,
			AdditionalParameterTypes: additionalTypes,
			Placement:                owner.Placement, ArtifactTargets: append([]string(nil), owner.ArtifactTargets...),
			Start: binding.start, Length: binding.length,
		})
	}
	for _, binding := range formBindings {
		component := ""
		for _, candidate := range components {
			if binding.target.Pos() >= candidate.Start && binding.target.End() <= candidate.Start+candidate.Length {
				component = candidate.Name
				break
			}
		}
		owner := componentByName[component]
		parts := strings.SplitN(binding.name, ":", 2)
		result = append(result, ValueCallbackBinding{
			Component: component, StatePath: append([]string(nil), binding.targetPath...),
			ValueProp: parts[0], CallbackProp: parts[1], CallbackValueType: binding.valueKind,
			Placement: owner.Placement, ArtifactTargets: append([]string(nil), owner.ArtifactTargets...),
			IntrinsicAdapter: binding.control + ":" + binding.event,
			Start:            binding.start, Length: binding.length,
		})
	}
	sort.Slice(result, func(left, right int) bool { return result[left].Start < result[right].Start })
	for index := range result {
		result[index].StatePath = nonNilSlice(result[index].StatePath)
		result[index].ArtifactTargets = nonNilSlice(result[index].ArtifactTargets)
		result[index].AdditionalParameterTypes = nonNilSlice(result[index].AdditionalParameterTypes)
	}
	return result
}

func componentBindingStateWrite(
	sourceFile *ast.SourceFile,
	target *ast.Node,
	typeChecker *checker.Checker,
) (StateWrite, bool) {
	for _, candidate := range componentCandidates(sourceFile) {
		if target.Pos() < candidate.node.Pos() || target.End() > candidate.node.End() {
			continue
		}
		aliases := collectComponentStateAliases(candidate, typeChecker)
		path, ok := statePath(target, aliases.bySymbol, typeChecker, true)
		if !ok || len(path) == 0 {
			return StateWrite{}, false
		}
		rootAlias, rootDepth := "", 0
		if stateWriteHasNestedThis(target, candidate.node) {
			rootAlias, rootDepth = stateWriteAliasRoot(target, aliases.bySymbol, typeChecker, target.Pos())
		}
		return StateWrite{
			Component:       candidate.name,
			Path:            path,
			Operation:       "assignment",
			Start:           target.Pos(),
			Length:          target.End() - target.Pos(),
			RootAlias:       rootAlias,
			RootDepth:       rootDepth,
			DynamicSegments: stateWriteDynamicSegments(target, path),
			Interaction:     true,
		}, true
	}
	return StateWrite{}, false
}

func typeContainsFlag(value *checker.Type, flag checker.TypeFlags) bool {
	if value == nil {
		return false
	}
	for _, member := range value.Distributed() {
		if member.Flags()&flag != 0 {
			return true
		}
	}
	return false
}

func notificationReturnType(value *checker.Type) bool {
	if value == nil {
		return false
	}
	for _, member := range value.Distributed() {
		if member.Flags()&(checker.TypeFlagsVoid|checker.TypeFlagsUndefined) == 0 {
			return false
		}
	}
	return true
}

func componentBindingDiagnostic(node *ast.Node, message string) Diagnostic {
	return Diagnostic{
		Severity: "error",
		Code:     "EXACT_COMPONENT_BINDING",
		Message:  message,
		Start:    node.Pos(),
		Length:   node.End() - node.Pos(),
	}
}
