// Code generated by scripts/generate-compiler-abi.mjs; DO NOT EDIT.

package exactcompiler

const (
	componentABICompiledRender = 1
	componentABILifecycle      = 2
	componentABILists          = 4
	componentABITasks          = 8
	componentABICollections    = 16
)
