// Code generated by scripts/generate-compiler-abi.mjs; DO NOT EDIT.

/** The compiled render arrow only constructs compiler-owned live readers once. */
export const compiledComponentRenderABI = 1;

/** The component registers authored lifecycle or resource-ownership work. */
export const compiledComponentLifecycleABI = 2;

/** The component uses the general runtime list capability. */
export const compiledComponentListsABI = 4;

/** The component needs task, interaction, or compatibility execution ownership. */
export const compiledComponentTasksABI = 8;

/** State or props can contain Map/Set values that require collection interception. */
export const compiledComponentCollectionsABI = 16;

/** The component boundary directly observes and reconciles one unstructured output reader. */
export const compiledComponentRangeOutputABI = 32;

/** The component reads or publishes values through its logical context chain. */
export const compiledComponentContextsABI = 64;

/** Every component capability bit accepted by runtime contract validation. */
export const allCompiledComponentABI =
	compiledComponentRenderABI |
	compiledComponentLifecycleABI |
	compiledComponentListsABI |
	compiledComponentTasksABI |
	compiledComponentCollectionsABI |
	compiledComponentRangeOutputABI |
	compiledComponentContextsABI;

/** Conservative non-render ABI used by explicit framework-owned boundary artifacts. */
export const generalComponentABI =
	compiledComponentLifecycleABI | compiledComponentListsABI | compiledComponentTasksABI;
