// Code generated by scripts/generate-compiler-abi.mjs; DO NOT EDIT.

/** Component record version accepted by this ABI generation. */
export const componentContractVersion = 1;

/** Render-program version accepted by this ABI generation. */
export const renderProgramVersion = 1;
