// Code generated by scripts/generate-compiler-abi.mjs; DO NOT EDIT.

/** Component record version emitted by the native compiler. */
export const componentContractVersion = 2;

/** Package build-facts protocol emitted by the compiler. */
export const componentLibraryProtocolVersion = 1;

/** Exact native process protocol implemented by this compiler host. */
export const nativeCompilerProtocolVersion = '1.0.0';
