/**
 * React Router 6.4+ and v7 share this facade. Explicit re-exports keep adapter
 * validation and generated declarations auditable while implementation remains
 * shared with the modern declarative facade.
 */
export {
  Await,
  BrowserRouter,
  Form,
  HashRouter,
  Link,
  MemoryRouter,
  NavLink,
  Navigate,
  Outlet,
  Route,
  Router,
  RouterProvider,
  Routes,
  StaticRouter,
  StaticRouterProvider,
  createBrowserRouter,
  createHashRouter,
  createMemoryRouter,
  createRoutesFromChildren,
  createRoutesFromElements,
  createStaticHandler,
  createStaticRouter,
  defer,
  generatePath,
  json,
  matchPath,
  useActionData,
  useAsyncError,
  useAsyncValue,
  useFetcher,
  useFetchers,
  useHref,
  useLoaderData,
  useLocation,
  useMatch,
  useMatches,
  useNavigate,
  useNavigation,
  useNavigationType,
  useOutletContext,
  useParams,
  useResolvedPath,
  useRevalidator,
  useRouteError,
  useRouteLoaderData,
  useRoutes,
  useSearchParams,
  useSubmit
} from "./modern.js";
export type {
  IndexRouteObject,
  NavigateOptions,
  NonIndexRouteObject,
  RouteObject,
  RouterProviderProps,
  StaticHandlerContext,
  To
} from "./modern.js";
