// Code generated by scripts/generate-compiler-abi.mjs; DO NOT EDIT.

/** Adapter marker package release accepted by dependency-range validation, not a wire-format version. */
export const reactCompatAdapterProtocolVersion = '0.6.1' as const;
